# Copyright 2024 - 2025 Khalil Estell and the libhal contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 游닍 Conan Package & Upload

on:
  workflow_call:
    inputs:
      library:
        type: string
        default: ${{ github.event.repository.name }}
      repo:
        type: string
        default: ${{ github.repository }}
      conan_version:
        type: string
        default: 2.18.0
      config2_version:
        type: string
        default: main
      version:
        type: string
        default: latest # "latest" means (do not upload)
      runner_os:
        type: string
        required: true
      arch:
        type: string
        required: true
      os:
        type: string
        required: true
      compiler_profile:
        type: string
        required: true
      dir: # Directory where the conan package exists
        type: string
        default: .
      remote_url: # Path to conan package repo
        type: string
        default: ""

    secrets:
      conan_remote_user:
        required: false
      conan_remote_password:
        required: false
jobs:
  package_and_upload:
    runs-on: ${{ inputs.runner_os }}
    env:
      VERBOSE: 1
      CONAN_REMOTE_USER: ${{ secrets.conan_remote_user }}
      CONAN_REMOTE_PASSWORD: ${{ secrets.conan_remote_password }}
    steps:
      - uses: actions/checkout@v4.1.1
        if: ${{ inputs.version != 'latest' }}
        with:
          submodules: true
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.version }}

      - uses: actions/checkout@v4.1.1
        if: ${{ inputs.version == 'latest' }}
        with:
          submodules: true
          repository: ${{ inputs.repo }}

      - name: 游닌 Install Conan ${{ inputs.conan_version }}
        run: pipx install conan==${{ inputs.conan_version }}

      - name: 游댌 conan version
        run: conan --version

      - name: 游니 Create and setup default profile
        run: conan profile detect --force

      - name: 游니 Add conan libhal remote
        run: conan remote add libhal https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: 游니 Add conan user remote-package-repo
        if: ${{ inputs.remote_url != '' }}
        run: conan remote add --force remote-package-repo ${{ inputs.remote_url }}
        # We use --force to allow the remote-package-repo to also be the libhal
        # repo.

      - name: 游니 Install libhal settings_user.yml
        run: conan config install https://github.com/libhal/conan-config2.git --args="-b ${{ inputs.config2_version }}"

      - name: 游닍 Create `Debug` package for ${{ inputs.profile }}
        run: conan create ${{ inputs.dir }} -s:h build_type=Debug -s:h os=${{ inputs.os }} -s:h arch=${{ inputs.arch }} --version=${{ inputs.version }} -pr:h ${{ inputs.compiler_profile }} --build=missing:cmake

      - name: 游닍 Create `MinSizeRel` package for ${{ inputs.profile }}
        run: conan create ${{ inputs.dir }} -s:h build_type=MinSizeRel -s:h os=${{ inputs.os }} -s:h arch=${{ inputs.arch }} --version=${{ inputs.version }} -pr:h ${{ inputs.compiler_profile }} --build=missing:cmake

      - name: 游닍 Create `Release` package for ${{ inputs.profile }}
        run: conan create ${{ inputs.dir }} -s:h build_type=Release  -s:h os=${{ inputs.os }} -s:h arch=${{ inputs.arch }} --version=${{ inputs.version }} -pr:h ${{ inputs.compiler_profile }} --build=missing:cmake

      - name: 游니 Sign into Conan Package Repository
        if: ${{ inputs.version != 'latest' && inputs.remote_url != '' && env.CONAN_REMOTE_USER != '' && env.CONAN_REMOTE_PASSWORD != '' }}
        run: conan remote login -p ${{ secrets.conan_remote_password }} remote-package-repo ${{ secrets.conan_remote_user }}

      - name: 游 Upload package version ${{ inputs.version }} to conan repo
        if: ${{ inputs.version != 'latest' && inputs.remote_url != '' }}
        run: conan upload "${{ inputs.library }}/${{ inputs.version }}" --confirm -r=remote-package-repo
